import = ["~/.local/share/alacritty-theme/themes/papercolor_light.toml"]

[window.padding]
x = 4
y = 0

[shell]
program = "/opt/homebrew/bin/bash"
args = ["-l"]

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
